### PR TITLE
static_assert the existence of an << ostream operator

### LINKED ISSUE #22: Better compile-time error messages
If a user calls `dbg(x)` with a value `x` of unsupported type `X`, the compiler prints a huge error message due to the missing `operator<<` overload:
```
error: no match for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘const X’)
   stream << value;
   ~~~~~~~^~~~~~~~

[… a lot of lines suggesting alternative overloads …]
```

If we could detect that `dbg(…)` is called with an unsupported type (*), we could potentially print a nicer error message.

(*) The check for whether or not a type is "supported" is actually a bit involved: it would require two stages:  (1) check if `X` is one of the "natively" supported types like `std::optional<T>` or *any* container type (2) check if `X` has an `operator<<` overload for `ostream`.

### PR DESCRIPTION
**Pull request by hmenke**
Fixes #22 (maybe only partially).

### CODE REVIEW

File: dbg.h [hunk 1]
```diff
@@ -189,12 +189,22 @@ struct has_begin_end_size {
...
+};
+
+
 // Specializations of "prettyPrint"
 
 template <typename T>
 typename std::enable_if<!has_begin_end_size<T>::value, bool>::type prettyPrint(
     std::ostream& stream,
     const T& value) {
+  static_assert(has_ostream_operator<T>::value, "Type does not support the << ostream operator");
```
Comment (sharkdp) [inline dbg.h]: should this maybe be `has_ostream_operator<const T&>::value`? Because `const T&` is the type of value that is supplied to `stream << ` below.

**Comment by sharkdp** [comment]
Nice! `is_detected` for the win :smiley: 

Unfortunately, the user will still see the `operator<<` compiler error from the `stream << value` line below. Could we maybe use a custom specialization/overload of `prettyPrint` for types without and ostream operator and just put the `static_assert` inside?

File: dbg.h (hunk 1 above)
Comment (hmenke) [reply dbg.h]: Yes, that is a good idea.

**Comment by hmenke** [comment]
I don't really see the advantage of suppressing the `stream << value` error message, because this is a classic case of adding more code complexity just for the sake of a nicer compiler error.  Anyway, I have implemented your request using a tag dispatch.

**Comment by hmenke** [comment]
Why does AppVeyor even run?  There is no `appveyor.yml`, so of course it fails immediately.

**Comment by xorz57** [comment]
@hmenke AppVeyor works even without `appveyor.yml` in the repository. They provide a "control panel" with everything you could write in `appveyor.yml`. If it doesn't find that file it uses the "online settings".

**Comment by sharkdp** [comment]
> @hmenke AppVeyor works even without `appveyor.yml` in the repository.

Oh, weird. I didn't know that. I now enabled the "Skip branches without appveyor.yml".

**Comment by sharkdp** [comment]
> I don't really see the advantage of suppressing the `stream << value` error message, because this is a classic case of adding more code complexity just for the sake of a nicer compiler error.

What do you mean by *"because this is a classic case of adding more code complexity just for the sake of a nicer compiler error"*? That was kind of the whole point of #22. I think better error messages (for the user) are a perfectly valid reason to justify an increase in amount of code / code complexity. Error messages are part of the UX. 

>  Anyway, I have implemented your request using a tag dispatch.

Thank you very much!

File: dbg.h [hunk 2]
```diff
@@ -196,14 +196,36 @@ struct has_begin_end_size {
...
+
 template <typename T>
 typename std::enable_if<!has_begin_end_size<T>::value &&
                             !std::is_enum<T>::value,
                         bool>::type
 pretty_print(std::ostream& stream, const T& value) {
-  stream << value;
+  pretty_print(
+      stream, value,
+      std::integral_constant<bool, has_ostream_operator<const T&>::value>{});
```
Comment (sharkdp) [inline dbg.h]: Awesome trick! I wouldn't have had any idea on how to fix this.
